name       : perl-file-basedir
version    : '0.08'
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/K/KI/KIMRYAN/File-BaseDir-0.08.tar.gz : c065fcd3e2f22ae769937bcc971b91f80294d5009fac140bfba83bf7d35305e3
license    : Artistic-1.0-Perl
summary    : Perl Freedesktop.org Base Directory implementation
component  : programming.perl
description: |
    This module can be used to find directories and files as specified by the Freedesktop.org Base Directory Specification. This specifications gives a mechanism to locate directories for configuration, application data and cache data. It is suggested that desktop applications for e.g. the Gnome, KDE or Xfce platforms follow this layout. However, the same layout can just as well be used for non-GUI applications.
patterns   :
    - /usr/share/man
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
