name       : perl-file-basedir
version    : 0.07
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/K/KI/KIMRYAN/File-BaseDir-0.07.tar.gz : 120a57ef78535e13e1465717b4056aff4ce69af1e31c67c65d1177a52169082b
license    : Artistic-1.0-Perl
summary    : Perl Freedesktop.org Base Directory implementation
component  : programming.perl
description: |
    This module can be used to find directories and files as specified by the Freedesktop.org Base Directory Specification. This specifications gives a mechanism to locate directories for configuration, application data and cache data. It is suggested that desktop applications for e.g. the Gnome, KDE or Xfce platforms follow this layout. However, the same layout can just as well be used for non-GUI applications.
patterns   :
    - /usr/share/man
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
