name       : perl-file-basedir
version    : '0.09'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-BaseDir-0.09.tar.gz : 6da6f7281562ac8f11ef1a3af6aedb51c41182b60f1f122ced0079efd92967d9
homepage   : https://metacpan.org/pod/File::BaseDir
license    : Artistic-1.0-Perl
summary    : File::BaseDir - Use the Freedesktop.org base directory specification
component  : programming.perl
description: |
    This module can be used to find directories and files as specified by the Freedesktop.org Base Directory Specification. This specifications gives a mechanism to locate directories for configuration, application data and cache data. It is suggested that desktop applications for e.g. the Gnome, KDE or Xfce platforms follow this layout. However, the same layout can just as well be used for non-GUI applications.
patterns   :
    - /usr/share/man
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
